name: godot4-gut-testing
description: Download GUT, import resources, run GUT tests for Godot 4 inside of Docker.
author: Hypasist
intputs:
  gutConfigPath:
    description: "Path to GUT config relative to directory"
    default: ''
  extraGodotFlags:
    description: "Extra flags passed to Godot."
    default: '--headless'
  importGodotResources:
    descritpion: "Tells, whether we should make addition Godot pre-run with '--import' flag set. Useful, if .godot folder is not included in Godot project repository."
    default: 'false'
branding:
  icon: git-merge
  color: blue

runs:
  using: "composite"
  steps:
    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
      
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        
    - name: Run COSTAM AKCJA
      run: echo "🖥️ The workflow is now ready to test your code on the runner."
      shell: bash      
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Testing ${{ github.repository }}/${{ github.ref }} on ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        id: checkouts
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      #  with:
      #    who-to-greet: 'Shelob, Child of Ungoliant'
      # Use the output from the `hello` step
      - name: Summary
        run: echo "Checkout time ${{ steps.checkouts.outputs.time }}\nTesting time ${{ steps.testing.outputs.time }}."
