name: godot4-gut-testing
description: Download GUT, import resources, run GUT tests for Godot 4 inside of Docker.
author: Hypasist
inputs:
  gutConfigPath:
    description: "Path to GUT config relative to directory"
    default: ''
  extraGodotFlags:
    description: "Extra flags passed to Godot."
    default: '--headless'
  importGodotResources:
    descritpion: "Tells, whether we should make addition Godot pre-run with '--import' flag set. Useful, if .godot folder is not included in Godot project repository."
    default: 'false'
branding:
  icon: git-merge
  color: blue

runs:
  using: "composite"
  steps:
    - name: Fantalone repository checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
    - name: GUT repository checkout
      uses: actions/checkout@v4
      with:
        repository: bitwes/Gut
        path: _gut
      run: echo "ALOHA"
      shell: bash
        
    - run: echo "$gutConfigPath $extraGodotFlags $importGodotResources"
      shell: bash
  
    - name: List files in the repository
      run: pwd && ls && echo $GITHUB_WORKSPACE && echo ${{ github.workspace }} && echo $NODE_ENV
      shell: bash
      
    - name: Random Number Generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
      
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
