name: godot4-gut-testing
description: Download GUT, import resources, run GUT tests for Godot 4 inside of Docker.
author: Hypasist
inputs:
  gutConfigPath:
    description: "Path to GUT config relative to directory"
    default: ''
  extraGodotFlags:
    description: "Extra flags passed to Godot."
    default: '--headless'
  importGodotResources:
    descritpion: "Tells, whether we should make addition Godot pre-run with '--import' flag set. Useful, if .godot folder is not included in Godot project repository."
    default: 'false'
branding:
  icon: git-merge
  color: blue

runs:
  using: "composite"
  steps:
    - name: Fantalone repository checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        
    - name: GUT repository checkout
      uses: actions/checkout@v4
      with:
        repository: bitwes/Gut
        path: _temp_gut
        
    - name: Moving GUT addons to the working folder
      shell: bash
      run: cp -R _temp_gut/addons . && ls addons && rm -rf  _temp_gut
      
    - name: Check Godot version
      shell: bash
      run: godot --version
              
    - name: Importing Godot resources
      shell: bash
      run: godot --headless --import --path .
      
    - name: Importing Godot resources
      shell: bash
      run: godot --headless --path . -s addons/gut/gut_cmdln.gd -gconfig ${{ inputs.gutConfigPath }}
